### ISSUE TITLE
Adding project stats in README.md

### ISSUE THREAD

**Issue by Ahsan-Ehtesham** [Ahsan-Ehtesham/Ecommerce-Store-using-NextJS#10]
You can add project stats like this in README.md document
![image](https://user-images.githubusercontent.com/52749230/194806226-33a2fc15-f784-4533-8936-880de9d3b692.png)

**Comment by Nzarite** [comment]
Hey @Ahsan-Ehtesham  I would like to contribute to this issue.
Please assign it to me.

**Comment by Shehryar-mallick** [comment]
I would like to contribute to this issue

**Comment by Shehryar-mallick** [comment]
Done please accept the pull request

**Comment by Nzarite** [comment]
@Ahsan-Ehtesham why didn't you assign this issue to me at the first. I was one who commented first. This is against the guidelines of hacktoberfest. I would report your repository.

**Comment by Ahsan-Ehtesham** [comment]
> @Ahsan-Ehtesham why didn't you assign this issue to me at the first. I was one who commented first. This is against the guidelines of hacktoberfest. I would report your repository.

Sorry didn't saw your comment

**Comment by Ahsan-Ehtesham** [comment]
> @Ahsan-Ehtesham why didn't you assign this issue to me at the first. I was one who commented first. This is against the guidelines of hacktoberfest. I would report your repository.

I have a new documentation issue **Contributors issue #12**, you can solve that
