### ISSUE TITLE
Contributors issue

### ISSUE THREAD

**Issue by Ahsan-Ehtesham** [Ahsan-Ehtesham/Ecommerce-Store-using-NextJS#12]
In readme.md, the documentation is showing only one contributor, fix this issue

**Comment by harsitagarwalla187** [comment]
Can i work in this issue?

**Comment by Ahsan-Ehtesham** [comment]
@harsitagarwalla187 Go ahead!

**Comment by harsitagarwalla187** [comment]
@Ahsan-Ehtesham I am unable to figure it out why the link is not working and showing only your picture. The format and all are correct. If you want me to add individually then i can do that.

**Comment by Ahsan-Ehtesham** [comment]
> @Ahsan-Ehtesham I am unable to figure it out why the link is not working and showing only your picture. The format and all are correct. If you want me to add individually then i can do that.

Exactly that's the issue, I want it to be dynamic so that if more people contribute later, it can automatically update

**Comment by Ahsan-Ehtesham** [comment]
Just checked the README.md, its gonna update after 24 hours hence closing this issue
