### ISSUE TITLE
it is not mobile responsive.

### ISSUE THREAD

**Issue by arjun-computer-geek** [Ahsan-Ehtesham/Ecommerce-Store-using-NextJS#15]
![Screenshot_20221011_022803](https://user-images.githubusercontent.com/50793512/194951480-fe9753f3-25fa-48ba-8746-cce1d54ac816.jpg)

Hey you can see here it is not responsive. Can I make the responsive. Please assign me to do.

**Comment by Ahsan-Ehtesham** [comment]
@arjun-computer-geek That's a nice issue, sure go ahead and fix this!
