### ISSUE TITLE
Wanted to add a product list on home page 

### ISSUE THREAD

**Issue by abhijain2003** [Ahsan-Ehtesham/Ecommerce-Store-using-NextJS#19]
Wanted to add a product list on home page for user to view product before signup/login please assign this under hacktoberfest 2022

**Comment by Ahsan-Ehtesham** [comment]
@abhijain2003 That's a good one!

**Comment by abhijain2003** [comment]
Hey brother I am finding a difficulty in getting product api 

can you help me 

I am trying to get it from getProduct.js file in api folder
but receiveing undefined when I console handler or connectdb function

**Comment by eldyl** [comment]
@abhijain2003 

Do you have the database setup locally using docker?

I just added a script to fill the database with mockdata that you can run by using `yarn seed`.

Most of the info on the home page seems to be in the Header component. You will need to use something like getServerSideProps in /pages/index.js and then pass the props to the Home component and down to the Header component. You should then be able to access product data in the Header component as props.

**Comment by abhijain2003** [comment]
thanks I try

well I don't have database setup locally using docker

**Comment by abhijain2003** [comment]
can you tell me how can i setup mongodb server to access data

**Comment by Ahsan-Ehtesham** [comment]
> can you tell me how can i setup mongodb server to access data

To start MongoDB Server:

start: docker compose up
stop: docker compose down
seed database: yarn seed

**Comment by abhijain2003** [comment]
but I do not have docker

**Comment by eldyl** [comment]
@abhijain2003 are you able to get Docker downloaded and going?

If not, I can finish this issue.

@Ahsan-Ehtesham One caveat: if this change is made, can you connect a mongo cluster for the preview? If we don't have any mock data in the preview, then the home page will be missing sections as well. This won't look very good. Data can be sourced from something like a hard coded array, but it is nice to see the db connected and working.

Let me know what you are thinking.

**Comment by abhijain2003** [comment]
go ahead i do not have any experience in docker

**Comment by jonathans199** [comment]
I've added a list of products coming from the database, to the home page under the header, here is the PR in regards

@Ahsan-Ehtesham 
https://github.com/Ahsan-Ehtesham/Ecommerce-Store-using-NextJS/pull/36

<img width="1777" alt="Screen Shot 2022-10-20 at 4 32 21 PM" src="https://user-images.githubusercontent.com/30424887/197052671-1bce6626-b4bb-4920-aa18-a7e95cea0cfa.png">

**Comment by jonathans199** [comment]
@Ahsan-Ehtesham review PR when you have a chance 👍
