### ISSUE TITLE
feat. Add navbar hover effect

### ISSUE THREAD

**Issue by hrsh22** [Ahsan-Ehtesham/Ecommerce-Store-using-NextJS#20]
Hey, I would like to add hover effects on navbar buttons.

**Comment by Ahsan-Ehtesham** [comment]
@hrsh22 Sure, Go ahead!

**Comment by singharyan1007** [comment]
Hi if this issue is still open can I work on it?

**Comment by Ahsan-Ehtesham** [comment]
> Hi if this issue is still open can I work on it?

@hrsh22 working on it!
