### ISSUE TITLE
Increasing the size of user-icon.

### ISSUE THREAD

**Issue by goodchai0** [Ahsan-Ehtesham/Ecommerce-Store-using-NextJS#24]
![1 05](https://user-images.githubusercontent.com/79858905/195081316-4c4c3203-facb-4815-aea7-ef3f4e302681.png)
![1 04](https://user-images.githubusercontent.com/79858905/195081340-0b2e8475-2cab-437e-963b-0ee9308839b5.png)

The user-icon is very small, I want to increase it. You can compare urself.
Please assign this to me under Hacktoberfest2022. @Ahsan-Ehtesham

**Comment by Ahsan-Ehtesham** [comment]
@goodchai0 sure, go ahead!

**Comment by goodchai0** [comment]
can you add "hacktoberfest-accepted" label too, otherwise the PR wont be counted.

**Comment by Ahsan-Ehtesham** [comment]
> can you add "hacktoberfest-accepted" label too, otherwise the PR wont be counted.

Already added it, no worries
