### ISSUE TITLE
Seed db script for dev environment/template preview

### ISSUE THREAD

**Issue by eldyl** [Ahsan-Ehtesham/Ecommerce-Store-using-NextJS#29]
Hello!

When working on sorting database items by category, I was adding items using Insomnia:

![add-products](https://user-images.githubusercontent.com/61209222/195144906-bc9f6f56-cb34-43cc-9634-ed8c5d28cdf0.png)

I would like to add a script, something like "yarn seed," that can be used to seed the database for development purposes.

@Ahsan-Ehtesham would you be interested in something like this? You could also utilize this script to create a mongo cluster for your preview. We could seed the cluster with this script. This would allow the site to show dummy products on the category pages in the deployment link. 

Currently, a 500 is received on the category pages:

![500](https://user-images.githubusercontent.com/61209222/195146130-2b622196-9323-4671-bc73-df528b0795d3.png)

**Comment by Ahsan-Ehtesham** [comment]
@dylanullrich That's a great idea, you can start working on it.

**Comment by eldyl** [comment]
Done with db fill script, but  I am working on better dynamic rendering of individual products according to slug. I will be submitting a PR shortly.
