### ISSUE TITLE
Adding backend functionality to Sign up page

### ISSUE THREAD

**Issue by Ahsan-Ehtesham** [Ahsan-Ehtesham/Ecommerce-Store-using-NextJS#3]
Signup page is ready, you have to add backend functionality to it

**Comment by DevoAbhi** [comment]
I can work on this. 
Do you have another backend repo?

**Comment by Ahsan-Ehtesham** [comment]
> I can work on this. Do you have another backend repo?

Next.Js doesn't need any other backend language, it itself supports backend

**Comment by ji2k** [comment]
I would like to working on this issue.

**Comment by Ahsan-Ehtesham** [comment]
@tzii Sure, Go ahead!

**Comment by jonathans199** [comment]
@Ahsan-Ehtesham 
I've added the Front-end functionality for both sign up and login. PR pending for that. 

How do you want to handle the backend?  when saving the users to Mongo via Mongoose?  JWT /  Hash password ok?

**Comment by Ahsan-Ehtesham** [comment]
> @Ahsan-Ehtesham I've added the Front-end functionality for both sign up and login. PR pending for that.
> 
> How do you want to handle the backend? when saving the users to Mongo via Mongoose? JWT / Hash password ok?

The data should save to mongoDB via mongoose upon signup then easily verify upon login, JWT will work good with this

**Comment by jonathans199** [comment]
> 

Ok I've added the login functionality with front and backend properly hashing the password into the mongo db. 

JWT implementation should maybe be another task, as this takes a secret frase etc...

**Comment by Ahsan-Ehtesham** [comment]
@jonathans199 Yeah sure, you can add JWT as another issue if you find it good for the project
