### ISSUE TITLE
Same products showing on all categories

### ISSUE THREAD

**Issue by Ahsan-Ehtesham** [Ahsan-Ehtesham/Ecommerce-Store-using-NextJS#8]
Amend the code such that different products come up in different categories

**Comment by jsvigneshkanna** [comment]
Please assign this my name, will work on it

**Comment by Ahsan-Ehtesham** [comment]
@jsvigneshkanna go ahead then

**Comment by RidhamRj** [comment]
Hey @Ahsan-Ehtesham  I will like to try to fix this issue
Kindly assign me
The previous assignee removed his name

**Comment by RidhamRj** [comment]
Basically I need to make the nav items tab right?
Or just keep it single page ?

**Comment by Ahsan-Ehtesham** [comment]
> 

The products must be coming dynamically using backend instead of being static

**Comment by RidhamRj** [comment]
Sry but I will be learning the backend stuff rn so it might take time 
It would be gr8 I will be able to learn new things

**Comment by eldyl** [comment]
I can work on this. Please assign.

**Comment by Ahsan-Ehtesham** [comment]
> I can work on this. Please assign.

Go ahead!

**Comment by eldyl** [comment]
#16

**Comment by Ahsan-Ehtesham** [comment]
Solved!
